use_frameworks!

platform :ios, '15.0'

target 'FavorletApp2App_Example' do
  
  #Cocoapods
  pod 'FavorletApp2App', '~> 1.0.1'
  
  #Local
#  pod 'FavorletApp2App', :path => '../'

  target 'FavorletApp2App_Tests' do
    inherit! :search_paths
    
  end
end
